"""update tagname field

Revision ID: 3453c1674139
Revises: 8e2cca3ec88b
Create Date: 2025-09-24 01:19:14.145821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3453c1674139'
down_revision: Union[str, Sequence[str], None] = '8e2cca3ec88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint(op.f('contents_user_id_fkey'), 'contents', type_='foreignkey')
    op.create_foreign_key(None, 'contents', 'users', ['username'], ['username'])
    op.drop_column('contents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key(op.f('contents_user_id_fkey'), 'contents', 'users', ['user_id'], ['id'])
    op.drop_column('contents', 'username')
    # ### end Alembic commands ###
