"""update tagname field

Revision ID: 6670a32a95d0
Revises: 741ba35d139d
Create Date: 2025-09-23 14:41:37.966653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6670a32a95d0'
down_revision: Union[str, Sequence[str], None] = '741ba35d139d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unuser',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unuser_id'), 'unuser', ['id'], unique=False)
    op.create_index(op.f('ix_unuser_username'), 'unuser', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unuser_username'), table_name='unuser')
    op.drop_index(op.f('ix_unuser_id'), table_name='unuser')
    op.drop_table('unuser')
    # ### end Alembic commands ###
