"""update tagname field

Revision ID: 8e2cca3ec88b
Revises: 6670a32a95d0
Create Date: 2025-09-23 19:14:33.384705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2cca3ec88b'
down_revision: Union[str, Sequence[str], None] = '6670a32a95d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unuser_id'), table_name='unuser')
    op.drop_index(op.f('ix_unuser_username'), table_name='unuser')
    op.drop_table('unuser')
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    op.create_table('unuser',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unuser_pkey'))
    )
    op.create_index(op.f('ix_unuser_username'), 'unuser', ['username'], unique=True)
    op.create_index(op.f('ix_unuser_id'), 'unuser', ['id'], unique=False)
    # ### end Alembic commands ###
