"""update tagname field

Revision ID: a69db098e718
Revises: 000dd6d5296c
Create Date: 2025-09-22 13:47:42.905504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69db098e718'
down_revision: Union[str, Sequence[str], None] = '000dd6d5296c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_tagname'), table_name='tags')
    op.create_index(op.f('ix_tags_tagname'), 'tags', ['tagname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_tagname'), table_name='tags')
    op.create_index(op.f('ix_tags_tagname'), 'tags', ['tagname'], unique=False)
    # ### end Alembic commands ###
