"""update tagname field

Revision ID: c9237857e1ee
Revises: 769809e5d00a
Create Date: 2025-09-24 13:53:48.114642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9237857e1ee'
down_revision: Union[str, Sequence[str], None] = '769809e5d00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('favicon', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('title', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('url_description', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('site_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'site_name')
    op.drop_column('contents', 'thumbnail')
    op.drop_column('contents', 'url_description')
    op.drop_column('contents', 'title')
    op.drop_column('contents', 'favicon')
    op.drop_column('contents', 'domain')
    # ### end Alembic commands ###
